### ISSUE TITLE
Add flexibility to model-group membership

### ISSUE THREAD

**Issue by jtwalsh0** [dssg/triage#108]
The current code defines a model group by hyperparameters (e.g. random forest with x trees, each of which is y deep, using gini to split, etc). But we should be able to define model groups to combine models with different hyperparameters.

An example of how this would be useful: it's January 1 and we need to choose a model. We decide to choose the most accurate model as measured through yesterday. That rule will probably choose a different model each year, e.g. in 2010 in might use a random forest, in 2011 a logistic regression, and in 2012 an extra trees. How well would we have done choosing that way?

**Comment by thcrock** [comment]
Moved to https://github.com/dssg/catwalk/issues/5
