### ISSUE TITLE
Make narrative documentation on readthedocs

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#109]

**Comment by mbauman** [comment]
http://triage.readthedocs.io/en/latest/

**Comment by thcrock** [comment]
We have started to build out the documentation site at https://dssg.github.io/triage/

A tutorial (which we'll link to from the documentation site, I'm sure) is being built in another repo: https://github.com/dssg/dirtyduck/tree/triage-tutorial

Individual additions to the documentation site should be in their own issues, and we should reevaluate what issues to create when the tutorial is done.

Closing this.
