### ISSUE TITLE
Store min_value and max_value for Metrics

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#129]
Thresholded metrics raise the issue of tied scores. For example, when calculating precision@10, 20 entities may share the highest risk spot. Which of these 20 should be included in the metric? Choosing different subsets may result in different values of precision if the entities have different labels. For cases like this, it would be good to store the maximum and minimum precisions calculated this way.

**Comment by thcrock** [comment]
This line that @k1aus brought up is key: https://github.com/dssg/triage/blob/master/triage/scoring.py#L252 - Currently the sorting is prioritizing the true labels (makes precision look better in these cases). Randomizing the ordering was brought up, though I agree evaluating all of them and providing the range provides a more clear (and reproducible) picture. 

What is the preferred way to query this in the database? Separate columns for min/max?, A range type (min/max)? Maybe even the full array?

**Comment by ecsalomon** [comment]
I like the idea of storing the full array (it might be useful to plot a
histogram, violin, or box plot of these values for models on some of the
comparison/evaluation plots), but one or two columns of summary (mode or
min+max or range) would also be good.

**Comment by thcrock** [comment]
The current idea for this is a separate metric/parameter, ie 'precision@300_min_abs'. We will deal with this at some point in the future.

The short-term bugfix is in https://github.com/dssg/triage/issues/133

**Comment by thcrock** [comment]
Moved to https://github.com/dssg/catwalk/issues/6
