### ISSUE TITLE
Add some batch performance information to a batches table

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#147]
Would be cool to have a batches table with some basic information:

- start time
- end time
- config hash
- n matrix jobs
- n matrices made
- n matrices skipped
- n modeling jobs
- n models trained
- n models skipped

Maybe some other things? @shaycrk

**Comment by ecsalomon** [comment]
Would also be good to have the output of pip freeze and the current hash of the repo's head. This would increase reproducibility.

**Comment by thcrock** [comment]
Can be added to the shiny new repository https://github.com/dssg/results-schema !

**Comment by thcrock** [comment]
Moved to https://github.com/dssg/catwalk/issues/8
