### ISSUE TITLE
ensure get_model_group_id creation in main branches

### ISSUE THREAD

**Issue by kenben** [dssg/triage#164]
The `get_model_group_id` stored procedure is not being automatically created if not available (https://github.com/dssg/triage/blob/master/triage/model_trainers.py#L289). That seems to have been fixed (among other things) by https://github.com/dssg/triage/commit/bc3dc47963d4e361b971d592284fcec7903c8e94, but that commit never made it into `master`.

**Comment by thcrock** [comment]
Moved to: https://github.com/dssg/catwalk/issues/9
