### ISSUE TITLE
state_config breaks backward compatibility (should be optional?)

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#171]
The change added in the **PR** #166 (about `state_config`)  should be optional or it will break the projects of `police-eis` and `sanjose housing` (since this projects doesn't have that section in their config files.

That section should be optional.

Also, I am not understanding correctly the need of this section. It seems very specific for some projects. Maybe it should be solved at "etl-time" by the user , not by `triage`

**Comment by thcrock** [comment]
We talked about this offline, but I'll recap:

- We did come up with a plan for allowing `state_config` to be optional: Basically, create a simple dense state table from the events table. 
- `police-eis` doesn't use the triage.Pipeline or triage config files, so they are unaffected by this change. When it does come time to convert their custom pipeline to use triage fully, I suspect that the `officer_past_activity_window` ( https://github.com/dssg/police-eis/blob/master/officer_config_collate_daily.yaml#L43 ) is functionality that the `state_config` here can be used for.
- `sanjose housing` does want to use this feature (SJ's need was the impetus for adding the feature), but hasn't yet as it is so new
- To my knowledge, this can not be handled at ETL time. The state configuration changes from experiment to experiment, and it affects what triage does internally as opposed to being a filter you can apply post-experiment.
