### ISSUE TITLE
Weird logging

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#185]
When training a model, `triage` logs the following:

 ```
WARNING:root:Starting train/test for 1 out of 11: train range: 2014-01-01 00:00:00 to 2014-04-01 00:00:00
WARNING:root:model meta data already stored 1
...
```

Why those are `WARNING`s instead of `INFO` or `DEBUG`?

**Comment by thcrock** [comment]
Agreed, `WARNING` was a mistake. I think to fit into similar messages they should be `INFO` level.

**Comment by hakoenig** [comment]
I think the warning:

>  WARNING:root:1year

is related to this. It is a warning that should be downgraded to DEBUG-level log message.

**Comment by thcrock** [comment]
I created and merged two PRs (in catwalk and triage) that handled this:

https://github.com/dssg/catwalk/pull/16
https://github.com/dssg/triage/pull/190
