### ISSUE TITLE
increase logging in triage and friends

### ISSUE THREAD

**Issue by rayidghani** [dssg/triage#195]

**Comment by thcrock** [comment]
Besides the commit that closed this issue, these also increased logging greatly:

https://github.com/dssg/architect/pull/43
https://github.com/dssg/catwalk/pull/26

We recommend increasing loglevel to logging.DEBUG and using this log format for more context:

`'%(asctime)s process=%(process)d %(filename)s:%(funcName)s %(levelname)s: %(message)s'`

For example:
```logging.basicConfig(
    level=logging.DEBUG,
    format='%(asctime)s process=%(process)d %(filename)s:%(funcName)s %(levelname)s: %(message)s'
)```
