### ISSUE TITLE
imputation options and dealing with nulls in collate

### ISSUE THREAD

**Issue by rayidghani** [dssg/triage#196]
a lot of this needs to happen in collate. For each feature, collate should passed an imputation method (zero, mean, group-mean, etc.) and collate should impute and create a new dummy column with 1s where the value for that feature was imputed and 0 otherwise.

**Comment by thcrock** [comment]
Most of the implementation of this will be covered by https://github.com/dssg/architect/issues/21

But we also have to figure out how exactly to control imputation in the config file, so at the very least we'll want to update the triage example_experiment_config in this issue.

**Comment by rayidghani** [comment]
a lot of this needs to happen in collate. For each feature, collate should passed an imputation method (zero, mean, group-mean, etc.) and collate should impute and create a new dummy column with 1s where the value for that feature was imputed and 0 otherwise.
