### ISSUE TITLE
Should allow several experiments at once

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#198]
If you try to run several experiments at once, you hit a race condition in the table `labels` and in the `features` schema.

One quick fix is create different schemas per experiment (using a hash), so every experiment should have their features and labels tables.

**Comment by thcrock** [comment]
@nanounanue There is a problem with this method: after the experiment is run, what schema would be used for applications like Tyra that want to read features? There would be no one place to look for feature values.

**Comment by thcrock** [comment]
Duplicate of #390, closing
