### ISSUE TITLE
Weird "bouncing" in the generation of as_of_date

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#201]
Weird "bouncing" in the generation of `as_of_date`.

It happens when the modeling time is not exactly divisible by the training period.

**Comment by thcrock** [comment]
I'm not sure, but this might be the same issue: https://github.com/dssg/timechop/issues/58

**Comment by thcrock** [comment]
This was done when timechop was merged into this repo: https://github.com/dssg/triage/pull/249 

Closing this
