### ISSUE TITLE
Triage should support the options all, leave-one-out and all-subsets feature_group_strategies

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#212]
Given the features groups `a, b, c`

"all" gives you `(a,b,c)`
"leave-one-out" should give you `(a,b) ,(a,c), (b,c)`
"allsubsets" should give you `(a), (b), (c), (ab), (ac), (bc), (abc`

**Comment by thcrock** [comment]
`all` and `leave-one-out` we have. This issue is just requesting an `allsubsets` strategy right?

**Comment by thcrock** [comment]
Closed by #518
