### ISSUE TITLE
Make timestamp range logic clear in state table documentation

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#236]
The format of the timestamp ranges in the state table isn't quite clear from the documentation. If you build the table with dates, Postgres assumes they are at midnight. If you build the table with dates and intend to have one-day ranges, you therefore need to have start and end be consecutive dates instead of the same date. We should make this clear in the example_experiment_config.

**Comment by jesteria** [comment]
@thcrock – To be sure, we're discussing the keys under `temporal_config`?

* feature_start_time
* feature_end_time
* label_start_time
* label_end_time

**Comment by thcrock** [comment]
Nope, this is not referring the value of any key in the config but rather the contents of the passed in state table.

I'm integrating this into the cohort config changes, so I'll take the issue. I'll add the couple of sentences that clarify this.
