### ISSUE TITLE
Allow a labels_table to be passed in instead of using an events_table

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#240]
Sometimes labels can be complicated to compute, and it is easier for the caller to pass in a precomputed labels table instead of having the Experiment compute them from events.

This requires some changes:
- the user has to know what as_of_times to compute, and the Experiment should aggressively ensure that all as_of_times specified by the temporal config are present
- The user has to both use a labeling window to generate their table but also pass one to Experiment (timechop still needs it). There could be leakage issues if the windows don't match up, and the Experiment can't check it on its own, so it should interactively prompt the user to confirm that the labelling window (and any other time config) matches up.
- The fallback for the states table config is to use events to make a (big) cross-product table for states. Without events, maybe we can use the passed-in labels table to figure out the states?

**Comment by shaycrk** [comment]
To the last point, I'm not actually sure if we can use the labels table to infer the states -- that would work in the case where all entities get labels, but not for inspections problems, only a subset of entities get labels but we need to make predictions on all of them.

**Comment by thcrock** [comment]
I'm in favor of dropping this in favor of #331 but I'm adding the label so we can discuss (one of them should be done)

**Comment by thcrock** [comment]
It seemed to be agreed that we would use the #331 method, so I'm closing this.
