### ISSUE TITLE
Heisenbug in fake_labels

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#263]
_From @thcrock on July 19, 2017 22:4_

When this code (in tests/utils.py):

```
def fake_labels(length):
    return numpy.array([random.choice([True, False]) for i in range(0, length)])
```

Comes up with all the same values, some of the metric calculators error out. We should just hardcode this to have some variation.

_Copied from original issue: dssg/architect#13_

**Comment by thcrock** [comment]
Fixed in https://github.com/dssg/triage/pull/397
