### ISSUE TITLE
Object-creation-time validation

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#283]
_From @thcrock on July 19, 2017 22:16_

Each component should implement basic validation of the creation-time arguments sent to it. When common problems will occur based on incorrect configuration, we want to be able to tell the user as soon as possible instead of waiting halfway through the experiment when the code fails.

_Copied from original issue: dssg/catwalk#2_

**Comment by thcrock** [comment]
Validation has been implemented. Closing this.
