### ISSUE TITLE
Add n_training_examples to results.models

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#288]
_From @thcrock on July 19, 2017 22:27_

Would be useful for comparing/filtering models to know how many examples each model was based on.

Would require a change in github.com/dssg/results-schema, but we'll have to use it here.

_Copied from original issue: dssg/catwalk#7_

**Comment by thcrock** [comment]
This really belongs in a matrices table. #274 is tracking the creation of this, and it already has n_examples in it. Closing this issue.
