### ISSUE TITLE
ensure get_model_group_id creation in main branches

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#290]
_From @thcrock on July 19, 2017 22:31_

From @kenben: "The get_model_group_id stored procedure is not being automatically created if not available (https://github.com/dssg/triage/blob/master/triage/model_trainers.py#L289). That seems to have been fixed (among other things) by bc3dc47, but that commit never made it into master"

_Copied from original issue: dssg/catwalk#9_

**Comment by thcrock** [comment]
This was eventually moved to the results schema, which is imported by the Experiment. The autocreation should happen then.

https://github.com/dssg/triage/blob/master/src/triage/component/results_schema/schema.py#L37-L44

Closing
