### ISSUE TITLE
Problem with storing data as HDF5 in connection with collate

### ISSUE THREAD

**Issue by k1aus** [dssg/triage#300]
The problem is that SQL alchemy reads collate output of aggregate functions as a number type with high precision, which requires reach column to be converted:

https://github.com/dssg/metta-data/blob/master/metta/metta_io.py#L200

This causes the storing of 400mb of memory pandas data frame to take 2 hours.

**Comment by thcrock** [comment]
That metta pull request needs to be reopened against this repo.

**Comment by thcrock** [comment]
The code that affects this is implemented in https://github.com/dssg/triage/blob/master/src/triage/component/catwalk/storage.py HDFMatrixStore.save - The fix linked to here is based on a very old version of code, and I'm not sure if it's still a problem. We should figure out if memory usage in the HDF saving is still an issue.

**Comment by thcrock** [comment]
My runtimes and memory usages between CSV and HDF on dirtyduck are very similar. I believe the work @nanounanue did to downcast data in the database fixed this. Experiment graphs attached.  Closing

![csv](https://user-images.githubusercontent.com/1649545/52294767-bea9fa80-293f-11e9-91c4-55f4b7950be6.png)

![hdf](https://user-images.githubusercontent.com/1649545/52294770-bfdb2780-293f-11e9-9722-ff2db8c93655.png)
