### ISSUE TITLE
Workflow without using combined aggregation table

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#306]
_From @thcrock on March 22, 2017 21:46_

Currently, calling `execute` on an Aggregation creates n tables, and then joins them together in a larger aggregation table.  The problem with this table is that it can get quite big and run afoul of the column limit. The smaller, pre-joined tables can be much more usable, but there are two problems with using them:

1. get_table_name returns only the aggregation tables, so to get the table names you want to have to perform some acrobatics, i.e. 'select table from information_schema' and then manually *remove* get_table_name() from that list.

2. execute still does the work of creating this table, which will only do unnecessary work but assumedly would fail in the column limit case.

Can we do something to make this workflow a bit better? I'd argue execute as a method name doesn't really make it clear what it does in the first place. It seems to do two things: creates group tables, and then creates an aggregation table. These would make sense to me as two exposed methods, like `aggregation.create_group_tables(), or aggregation.create_aggregation_table() which calls self.create_group_tables before creating the aggregation table. Either method would return the pertinent list of tables.

What do you think? 

_Copied from original issue: dssg/collate#75_

**Comment by jesteria** [comment]
_From @mbauman on March 22, 2017 22:39_

Is your intention here to effectively replace the aggregation tables with timechop?  I think that makes sense — I might go even farther and limit collate's scope to just creating the feature tables and allow downstream tools to handle the joining.

There will soon be another operation — creating the meta tables.

**Comment by jesteria** [comment]
_From @thcrock on March 23, 2017 1:56_

Well, I'm thinking more conservatively than removing the joining, because I figure if it works for other users than I don't see a reason to touch it, at least not yet. Especially since timechop is pretty early-stage; I wouldn't recommend our joining mechanism to others right now.

**Comment by thcrock** [comment]
No longer relevant, Triage uses the combined aggregation table now. Closing
