### ISSUE TITLE
Override generation of imputated flag

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#310]
_From @shaycrk on September 20, 2017 16:34_

We may want to allow for overriding the generation of an imputed flag, for instance, in cases where zero-filling is meaningful (e.g., for count features created from a table of arrests, entities not in the table have no arrests, so 0 is in fact the correct value).

_Copied from original issue: dssg/collate#103_

**Comment by thcrock** [comment]
Done in #230 - closing
