### ISSUE TITLE
Lookup values for categoricals

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#311]
_From @thcrock on March 3, 2017 17:29_

A common pattern is that the feature names we want to use in categoricals reside in lookup tables, whereas the value present in the main table is simply an id.

From what it seems to me, the only way to solve this using the categorical is to make the from_obj in the SpacetimeAggregation a join, or potentially many joins. This can introduce query time issues, and potentially having to introduce a bunch of aliases to make it make the names make sense, if the join tables have a similar column naming format.

It would be nice to allow this more easily within the Categorical class itself.
1. One interface could be an optional dict passed in which maps from ids to names (ie "case when color_id = 1 then color = 'blue' end").
2. Another is to make the 'choices' input optionally be a dict, and work similarly to 1 internally.

What do you think?

_Copied from original issue: dssg/collate#67_

**Comment by jesteria** [comment]
_From @mbauman on March 3, 2017 18:20_

2 is already implemented!

```python
In [23]: c = Categorical('color_ids', {'blue': 1, 'red':2, 'yellow':3}, ['sum'])

In [24]: st = SpacetimeAggregation([c], from_obj='table', groups=['ids'], intervals=['1y'], dates=['2016/01/01'])

In [25]: map(str, st.get_selects()['ids'])
Out[26]: ["SELECT ids, '2016/01/01'::date AS date, sum(CASE WHEN date >= '2016/01/01'::date - interval '1y' THEN (color_ids = 3)::INT END) AS table_ids_1y_color_ids_yellow_sum, sum(CASE WHEN date >= '2016/01/01'::date - interval '1y' THEN (color_ids = 1)::INT END) AS table_ids_1y_color_ids_blue_sum, sum(CASE WHEN date >= '2016/01/01'::date - interval '1y' THEN (color_ids = 2)::INT END) AS table_ids_1y_color_ids_red_sum \nFROM table \nWHERE date < '2016/01/01'AND date >= '2016/01/01'::date - greatest(interval '1y') GROUP BY ids"]
```

**Comment by thcrock** [comment]
As mentioned in the comment, this is done. Closing
