### ISSUE TITLE
Remove code in metta module that is deprecated

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#312]
_From @avishekrk on July 21, 2017 22:19_

_Copied from original issue: dssg/metta-data#44_

**Comment by thcrock** [comment]
I believe that the way Triage is using metta, these are deprecated. We can remove this code from the new Triage-housed metta module. I'm renaming this to cover more removal of deprecated code. For instance, uploading to s3 isn't really needed as we have S3 support without even bothering with a filesystem.
