### ISSUE TITLE
Revisit public/private methods

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#315]
_From @ecsalomon on March 14, 2017 19:52_

Speedy development got a bit sloppy. Good idea to revisit what should be public/private methods and make sure there are tests for the public ones.

_Copied from original issue: dssg/timechop#12_

**Comment by jesteria** [comment]
_From @thcrock on July 25, 2017 18:41_

Test coverage post-https://github.com/dssg/timechop/pull/72 will be 100%, but a point here still stands about public vs private methods. It's unclear whether the non-chop_time methods are part of the interface or just internal. I'll change the name of the issue.

As far as the parts of the codebase that have been moved to the Architect repo since this issue was created, test coverage and public/private demarcation looks like it's been addressed over time, so I won't recreate a version of this there.

**Comment by thcrock** [comment]
I think when timechop was rewritten this was addressed to the extent that it makes sense for such an old issue. If we think that there needs to be further refactoring in the timechop code, we should open a ticket that is more specific to the current code. Closing
