### ISSUE TITLE
Add an example config and script

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#317]
_From @ecsalomon on May 3, 2017 22:39_

Much of this can be cribbed from triage and San Jose.

_Copied from original issue: dssg/timechop#67_

**Comment by thcrock** [comment]
This only made sense as a separate example when timechop was a separate repository. The timechop deep dive, tracked in #314 , will have examples, but as far as a script goes we're just not going out of our way to expose Triage components as separate from Triage itself now. Closing.
