### ISSUE TITLE
Utility to get initial lists

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#321]
_From @thcrock on July 26, 2017 23:9_

Provide some functionality for getting train_end_date and model_group_id lists with some typical options

Sounds like this is what we were reserving the name 'casting call' for.

_Copied from original issue: dssg/audition#8_

**Comment by jesteria** [comment]
_From @thcrock on October 12, 2017 20:41_

Object that takes in as kwargs:

- model group info
- batch run time
- model comment
- exp hash
- hash of feature list in mg

And spits out model group ids

For train end times, take in these model group ids and get common options. Verify that each model group has each train end time (and an evaluation for it).

**Comment by thcrock** [comment]
Basic Pre-Audition functionality was merged in #362 - Closing this
