### ISSUE TITLE
Problem with DummyClassifier and Individual Feature Importance

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#360]
https://github.com/dssg/triage/blob/72c240c58d910399765fddb2ea8171ea2321fbb8/src/triage/component/catwalk/model_trainers.py#L156

It throws this error:

`KeyError: 'Algorithm does not support a standard wayto calculate feature importance.' `

SUGGESTION: Individual feature importance should be optional...

**Comment by nanounanue** [comment]
This was closed by @hakoenig 

Could you add the number of *pull request* and close it @hakoenig ?

**Comment by hakoenig** [comment]
closes #379

**Comment by thcrock** [comment]
Cleaning this up per @hakoenig 's comment
