### ISSUE TITLE
Catwalk version is set to >=0.3 instead of ==0.3

### ISSUE THREAD

**Issue by k1aus** [dssg/triage#384]
https://github.com/dssg/triage/blob/57243b95f06dae9c94186648bfa66718bbc3e8b3/requirements.txt#L19

**Comment by thcrock** [comment]
will want to branch off of 1.0.2 and tag a 1.0.3. this isn't applicabe to master

**Comment by thcrock** [comment]
We solved this for the project by moving off of 1.0.2 to a new version which doesn't have this problem. Closing
