### ISSUE TITLE
Redesign Schemas, Introduce Training Results Tables

### ISSUE THREAD

**Issue by jack-barbey** [dssg/triage#394]
Schemas and tables affected: (* indicates new addition)
`model_metadata` (formerly `results`)
- models
- model_groups
- experiments
- list_predictions
- *matrices

*`test_results`
- test_predictions (formerly `predictions`)
- test_evaluations (formerly `evaluations`)
- individual_importances

*`train_results`
- *train_predictions
- *train_evaluations
- feature_importances

**Comment by ecsalomon** [comment]
For features, I think the feature metadata table will have things like aggregation function, aggregation time, from_obj, etc. Feature importances seem like train results to me.

**Comment by jack-barbey** [comment]
Thanks, @ecsalomon. I moved feature_importances to train_results.

**Comment by thcrock** [comment]
done in https://github.com/dssg/triage/pull/397
