### ISSUE TITLE
Experiment should log time of execution and its status

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#403]
`Experimen` should log:

- `created_at`
- `start_running_at`
- `end_running_at`
- `final_status` (i.e. `COMPLETED`, `FAILED`, `WAITING`)

**Comment by thcrock** [comment]
Is this referring to putting the information in a database table, or just a log message?

If database we did talk about this before as a 'batches' table: https://github.com/dssg/triage/issues/289

**Comment by thcrock** [comment]
It is worth thinking through how this relates to partial config and runs. What is they just run timechopping or and label creation? Should there be any row at all in this case? Or a row that has the name of the most recent phase that was run?
