### ISSUE TITLE
database configuration via process environment (replace database.yaml)

### ISSUE THREAD

**Issue by jesteria** [dssg/triage#419]
As a user of Triage, I would greatly prefer the flexibility of specifying my database access parameters via the process environment – to be exact, via the database URI format [[example]](http://docs.sqlalchemy.org/en/latest/core/engines.html#database-urls) – over doing so via the _additional_ and separate configuration file, which defaults to `database.yaml`.

1. These parameters are likely environment-specific and -variable. I do not want to manage a separate, custom environment-dependent file.
2. These parameters likely contain **secrets**. I want the flexibility to specify these elsewhere than on disk.
3. I want the flexibility to specify these parameters using all the tricks of the *nix trade, **composing** them even, as makes sense for me

Maybe I want a development-only `.envrc`/`.env`/*etc.* file in my repository root – I'll keep values specific to that environment there.

…But I don't want passwords *anywhere*. It's up to the developer to ensure that's provided – in their `.bashrc` or personal env file or upon invocation: `DATABASE_URL=… manage audition`.

(And _my_ app or my `.envrc` can detect environmental variables like `POSTGRES_PASSWORD` and `DATABASE_PASSWORD` and compose these into my final `TRIAGE_DATABASE` or `DATABASE_URL`.)

…And in production, that's another story. In fact, the possibilities are endless.

---

Moreover, as a developer of Triage, I want to receive this information from a single, standard interface, and for that information to already be in the standard format I require – that of a database URI.

1. Database access parameters would need no longer be carried through from the particular interface, (which may be `Experiment(…)` or the CLI or I don't know what…), down, down, down to the frame that needs it
2. Many instances across the codebase of `yaml.load(…)` and `URL(…)`  could be removed.

---

* Generally, where we now accept a database **engine**, we should continue to do so. This allows for the height of configurability.
* However, wherever we now look to a database **file**, we should first check the process environment for the one argument in which `create_engine` is interested – the database URI.
    * For backwards compatibility, and perhaps to support situations that could actually use it, we can fall back to looking for such a file in the current working directory
    * If there's actually any anticipated need, we could also look in the process environment and/or in some *other* existing configuration file for the path to a database.yaml; however, it seems unlikely that there would be need for this.
* If still necessary, this in-Triage engine-creation should be centralized, such that such decisions as to where to look up the database access parameters can easily be adapted.

**Comment by nanounanue** [comment]
I complety agree with this, actually in `dirtyduck` we use the `URI`:

https://github.com/dssg/dirtyduck/blob/5b19764760baa2a7cb81f8af23d875fedd776103/infrastructure/triage/triage_experiment.py#L34

**Comment by jesteria** [comment]
Resolved by #605 

Note, that doesn't include discussion of Triage _internals_ -- this only resolves the CLI's explicit dependence on a `database.yml`. However, we should feel free to reopen this (likely under a new issue), if/when we find there's need to refactor Triage internals, and/or to add additional support for Triage library users (who should as is be able to read database connection information from wherever they like).
