### ISSUE TITLE
Show tracebacks if CLI errors

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#455]
If the CLI has an uncaught exception, currently the user just gets the one-line exception, which is only marginally helpful. This should be the entire traceback.

**Comment by thcrock** [comment]
Combing through argcmdr, it looks like you can enable this with `--traceback` but we should make it more clear. It doesn't show up in the help, when I think it should

**Comment by jesteria** [comment]
It's true, such tracebacks are vital to developers. But `argcmdr` **does** add the `--traceback` flag to the root parser, by default, as well as the abbreviated flag `--tb`.

The current `triage` CLI help text I see is:

    usage: triage [-h] [--tb] [-d DBFILE]
                  {configversion,showtimechops,featuretest,experiment,audition,db}
                  ...
    
    manage Triage database and experiments
    
    optional arguments:
      -h, --help            show this help message and exit
      --tb, --traceback     print error tracebacks
      -d DBFILE, --dbfile DBFILE
                            database connection file
    
    triage commands:
      {configversion,showtimechops,featuretest,experiment,audition,db}
                            available commands
        configversion       Check the experiment config version compatible with
                            this installation of Triage
        showtimechops       Visualize time chops (temporal cross-validation
                            blocks')
        featuretest         Test a feature aggregation by running it for one date
        experiment          Run a full modeling experiment
        audition            Audition models from a completed experiment to pick a
                            smaller group of promising models
        db                  Manage experiment database

**Comment by thcrock** [comment]
This works
