### ISSUE TITLE
Batch-fix PEP8 errors

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#460]
We currently enforce PEP8 in Travis, but it only gets lines that have been changed. There are still many incriminating lines, and this hinders our capability to check entire files or the whole repo at once with flake8.

Perhaps we can use something like https://github.com/hhatto/autopep8 to try and fix them all in one go? I haven't worked with tools like that before so I'm not sure how well they work.

At the end of this issue the command `flake8 src` should work without error.

**Comment by ecsalomon** [comment]
Just piping in that I've been looking at https://github.com/ambv/black It is even a bit stricter than PEP8, so there are some stylistic choices that not everyone would necessarily agree with (but I generally like). I also haven't tried black or autopep8, so don't know how well it works in practice.

**Comment by thcrock** [comment]
Closed by #470
