### ISSUE TITLE
S3ModelStorageEngine mangling storage path

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#461]
`pathlib.PurePosixPath()` drops one of the forward slashes in the S3 model storage path, making it unreadable by botocore, which gives this error:

```
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "s3:": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$"
```

Here is an example from the console of the output from `pathlib.PurePosixPath()`:

```
>>> str(pathlib.PurePosixPath('s3://example-bucket/example_project', 'models', 'abc'))
's3:/example-bucket/example_project/models/abc'
```

**Comment by thcrock** [comment]
I'm having trouble reproducing this on master, where it looks like we remove the 's3://' prefix entirely before putting it through PurePosixPath (and we don't even have an S3ModelStorageEngine class anymore). I would like to work with you to see how exactly this is surfacing in Triage.

**Comment by ecsalomon** [comment]
This may have arisen from using the 408 reloaded branch. Now that that is merged, I will try again from master.
