### ISSUE TITLE
Failed experiments not cleaning up temporary state table

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#466]
When I run an experiment after a failed experiment, I get a temp state table still exists error.

**Comment by ecsalomon** [comment]
Ah, I see that this is a user error. The `cleanup` default is `False`, and I did not set it to `True`. But I wonder if the default should be `True`.

**Comment by thcrock** [comment]
I think there's a good argument for that, but there's also an argument for ability to debug said error if it's related to the state table. Leaving the table after an error allows us to more easily debug the error later, without making the user re-run. But even if this is so, it should probably remove it at the beginning of the next run of that particular experiment.

**Comment by ecsalomon** [comment]
That seems like a satisfactory solution to me.

**Comment by thcrock** [comment]
Should be closed when #537 is done
