### ISSUE TITLE
showtimechops CLI option not working

### ISSUE THREAD

**Issue by ivanhigueram** [dssg/triage#512]
When running `triage -d <db_creds> showtimechops <configuration_file.yaml>` Triage run the time chops, but do not display or save any plot. It would be a good idea to save them in the `project_path` directory when the `--project-path` is specified.

**Comment by ivanhigueram** [comment]
Oh! I just saw that. I'm calling the plotter directly and save it directly to a `timechops` folder. I guess we can hardcode it (as `Audition`), or define a flag for saving.

**Comment by thcrock** [comment]
If you're doing the work to actually save it, I think you should run it through the `ProjectStorage` class if you're not doing so already.

**Comment by nanounanue** [comment]
@thcrock Could you point to an example of using the `ProjectStorage` class? 

Should the image be stored always? That will simplify the arguments of the CLI, since  we *only* need to add the `--project-path` argument

**Comment by jesteria** [comment]
Did we ever figure out why it wasn't showing the plot?

That it's initiated through the CLI library "shouldn't" be a problem; (though, there could be something wrong there).

At least as probably, the "show" expressions assumed something? Perhaps that they're run from `ipython`, or something like that?
