### ISSUE TITLE
plot_feature_importances_std_err() doesn't work with DT classifier

### ISSUE THREAD

**Issue by alenastern** [dssg/triage#516]
On line 517 of model_evaluator.py, get error "AttributeError: 'DecisionTreeClassifier' object has no attribute 'estimators_'" when run plot_feature_importances_std_error() on a decision tree classifier. Need to add note that can only be used with random forest (and I think also gradient boosting) @ivanhigueram

**Comment by ivanhigueram** [comment]
I'll add a warning 😄
