### ISSUE TITLE
s3fs cannot write matrices larger than 5GB

### ISSUE THREAD

**Issue by alenastern** [dssg/triage#530]
My experiment is failing with the following error messages:

```
botocore.exceptions.ClientError: An error occurred (EntityTooLarge) when calling the PutObject operation: Your proposed upload exceeds the maximum allowed size

raise_from(IOError('Write failed: %s' % self.path), e)

OSError: Write failed: dssg-mined/triage/matrices/806e442c7322bb92ad2d07f76220c51d.csv
```

This seems to be because s3fs does not support the multipart file uploading option on boto3 which means we cannot upload matrices larger than 5GB to S3.

**Comment by nanounanue** [comment]
With the last version of `triage` (v3.2.0), this came back. The behavior now is that is not interrupting the execution, just prints the error and continues (The past behavior was throw the error and then stop the experiment)

**Comment by alenastern** [comment]
I'm also experiencing issues with reading large models from S3 - read fails at ~ 5GB though experiment still continues to "SUCCEEDED" status on batch. Model successfully wrote to S3 at 23GB size.

CloudWatch Log: 
`urllib3.connectionpool 22/01/2019 08:53:33 PM DEBUG 495 connectionpool.py 393: https://dssg-mined.s3.us-west-2.amazonaws.com:443 "GET /triage/trained_models/f4798b568e1a94f2e93f24577bb28a21 HTTP/1.1" 206 5251072`
`root 22/01/2019 08:53:42 PM ERROR 1 multicore.py 133: Child failure`

Batch message `Reason: OutOfMemoryError: Container killed due to memory usage`

**Comment by thcrock** [comment]
Looking at the last one, I'm not sure that's related to the download, or at least boto. It honestly just looks like the worker got killed because it ran out of memory.
