### ISSUE TITLE
Update the learner grid in the example config

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#543]
Many projects start out by copying an existing grid config from a previous project or the triage example. But some of the learners or hyperparameters explored in older projects or in the example config may not be good first steps for a new project. We should develop a standard good (average) "starter pack" and use that in the example config (with the obvious caveat that projects may occasionally deviate from this initial configuration for idiosyncratic reasons). This should save us computation resources and analysis time.

**Comment by nanounanue** [comment]
Solved in ea31788b01de4421afb20ac6a4441e2a11659904
