### ISSUE TITLE
Collate produces redundant imputation flags

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#544]
The imputations for a categorical or quantity will be the same for the same aggregation period, regardless of aggregation function. This produces a lot of redundant columns. For example, the following features will have exactly the same imputation flag columns:

- Average test score in the last three years
- Max test score in the last three years
- Minimum test score in the last three years
- Standard deviation of test score in the last three years
- Modal test score in the last three years

Collate should add _only one_ imputation column per quantity/categorical per aggregation period.

**Comment by thcrock** [comment]
I'm guessing we should name the _imp column similarly but without the aggregate function?
e.g.

`zip_code_features_zip_code_1year_num_events_min_imp`
`zip_code_features_zip_code_1year_num_events_max_imp`

become
`zip_code_features_zip_code_1year_num_events_imp`
?
