### ISSUE TITLE
ModelGrouper needs to listify feature names

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#551]
To make the stored procedure call work, the ModelGrouper uses the string representation of a list in assembling the query. This conflicts with the new changes in #547 to make the string representation more compact.

**Comment by jesteria** [comment]
We should really avoid using the Python default representations as PostgreSQL / database-appropriate representations (in part for this reason) – SQLAlchemy helps with this, interpolating the correct representation.

(But obviously this works for now :+1: )

**Comment by thcrock** [comment]
Yeah I agree.

I think the real solution is getting rid of the stored procedure so until we do that I'm satisfied to only do the very minimal fixes for bugs relating to it.
