### ISSUE TITLE
Missing link between model and test data (if you don't store the predictions)

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#591]
Running `triage` without storing the predictions (in CLI: `--no-save-predictions` flag) *apparently* "breaks" the connection between model and test matrix.

What do I mean by "breaks" is that (again, *apparently*) there is no way to see, in the DB in which matrix the model was tested.

Originally, one possible query to do that was:

```sql
select distinct
    model_id,
    model_group_id, train_end_time,
    model_hash,
    pr.matrix_uuid as test_matrix_uuid,
    ma.num_observations as observations,
    ma.lookback_duration as feature_lookback_duration,  ma.feature_start_time
from
    model_metadata.models as mo
    join
    test_results.predictions as pr using (model_id)
    join
    model_metadata.matrices as ma on pr.matrix_uuid = ma.matrix_uuid
order by
    model_group_id, train_end_time asc;
```

Any ideas?

**Comment by thcrock** [comment]
This brings up a good point. I think that the evaluation tables should have the matrix uuid just like the predictions table has.

As far as how to achieve this now, I think you could do a JSON join from specific fields in the matrix_metadata column in the matrices table and columns from the evaluation table.

**Comment by nanounanue** [comment]
I totally agree with you, Should I rename the issue?

**Comment by thcrock** [comment]
Sure, and add it to the project in the "let's do" column.
