### ISSUE TITLE
Triage CLI doesn't read experiment files stored in S3

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#598]
`triage` supports this feature, but when used from the CLI it fails with:

```
triage experiment: error: argument config: can't open 's3://dsapp-dirtyduck/experiments/simple_test_skeleton.yaml': [Errno 2] No such file or directory: 's3://dsapp-dirtyduck/experiments/simple_test_skeleton.yaml'
```

even when the file is in the bucket.

**Comment by thcrock** [comment]
My guess is the argparse filetype is doing this. We should switch the project path to a regular string

**Comment by thcrock** [comment]
My bad. Not project path. This is the experiment file. Still, fix would be the same. Use Store.factory to handle the string argument instead of argparse.filetype

**Comment by nanounanue** [comment]
Ok. So the fix should be in the `cli` or in the in `experiment` source file?

**Comment by jesteria** [comment]
`cli` -- it thinks you're only ever handing it a local file system path, and attempts to load it eagerly, when in fact you're passing it an S3 path.
