### ISSUE TITLE
Add last run timestamp to experiments table

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#613]
It would be nice to be able to answer a question like "What's the hash of the experiment I just ran?" with a query like:

```sql
select last_run_time, experiment_hash
from model_metadata.experiments
order by last_run_time desc
limit 1;
```

**Comment by nanounanue** [comment]
It would be better to have a table with the runs and the final estatus

**Comment by nanounanue** [comment]
Or also have like the stages (matrix creation, training, etc) and the time

**Comment by thcrock** [comment]
Yeah we keep coming up with other things to prioritize over https://github.com/dssg/triage/issues/440 but I think its time we go ahead and do that one

**Comment by ecsalomon** [comment]
👍 closing in favor of #440
