### ISSUE TITLE
Postmodeling: Add stack ranking/calibration plot

### ISSUE THREAD

**Issue by shaycrk** [dssg/triage#654]
Lower priority, but one plot I find helpful and easy to explain to non-technical audiences is the stack-ranking performance of the model (e.g., splitting the test set by deciles or vigintiles and looking at how the average score compares to the average label in each as a bar graph). This can be used to look at calibration or simply show that the model is ranking properly and how the propensity differs from top to bottom.

**Comment by avishekrk** [comment]
Is this a duplicate of #179 ?

**Comment by shaycrk** [comment]
I had a slightly different, but definitely closely related plot in mind. Will close this one and add my comment to that issue...
