### ISSUE TITLE
In an experiment run, check db, don't upgrade db

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#695]
If you install a new version of triage and try to run an experiment, the current behavior is to upgrade the database at that time. For databases with a large number of models and predictions, this can launch an extremely time-consuming (and potentially undesirable) process without warning the user.

Instead, _check_ the db version and raise an error if it is incorrect, with a helpful error message warning users that upgrading (especially the predictions) can be time-consuming.

**Comment by jesteria** [comment]
We also discussed whether the check should either:

1. prompt the user: `migrate db? [Y|n]`
2. simply fail with the error, and accompanying advice: `upgrade/migrate the db via the CLI: triage migrate`

(or what-have-you).

(1) might be nice, but assumes that processes are launched via an interactive terminal, (which is likely often not the case).

Hence (2) _might_ be safer and more appropriate, to just ensure that the error is reported/logged appropriately and with sufficient remediation advice.

**Comment by ecsalomon** [comment]
`... or downgrade triage ¯\_(ツ)_/¯`
