### ISSUE TITLE
Triage error with no bias config

### ISSUE THREAD

**Issue by shaycrk** [dssg/triage#706]
@lorenh516's triage test runs of NC data are hitting an error in evaluations because she is not passing bias config for aequitas.

It looks like this is because `catwalk.evaluation.py` is attempting to check for `protected_df is not None` [here](https://github.com/dssg/triage/blob/e47f07a251b29cb936677a4eb29355036da437d5/src/triage/component/catwalk/evaluation.py#L520) but will be passed an empty `DataFrame` by `ProtectedGroupsGeneratorNoOp` (rather than `None`) when no bias configuration has been specified.

@thcrock or @saleiro -- Is the better solution here to check for an empty dataframe in `catwalk.evaluation.py` of return `None` from `ProtectedGroupsGeneratorNoOp`?

**Comment by thcrock** [comment]
@shaycrk Your PR fixed this right?

**Comment by shaycrk** [comment]
Oh, weird -- I thought it was a general github feature that adding `closes #XXX` in the PR title would close the associated issue on merge! Anyway, yeah, I'll go ahead and close this.
