### ISSUE TITLE
I cannot run the tutorial.sh

### ISSUE THREAD

**Issue by JoaoCarabetta** [dssg/triage#715]
I was super excited that I finally got time to run triage.

Buuut, I couldn't get to the second step of the tutorial.

In the step

`./tutorial.sh start`

I got a `ERROR: Couldn't find env file: /Users/joaoc/Documents/Projects/triage/docs/sources/dirtyduck/.env` as an answer.

Did I miss something? I checked the directory but there is no `.env` file.

I am using a Mac.

**Comment by nanounanue** [comment]
@JoaoCarabetta Could you try with the new version? I just ran it:

`tutorial.sh up`

and it created the database without a problem.

**Comment by nanounanue** [comment]
Closed in a8a8388d9a04a1e39bb918935d0b9262bb85a703
