### ISSUE TITLE
Create utility for generating config from config directory structure

### ISSUE THREAD

**Issue by ecsalomon** [dssg/triage#73]
As features are added, this section of the config quickly grows to several hundred to a few thousand lines. It might be more readable to source features from separate config files, either a single config for all features or one file per `from_obj`. (See https://github.com/dssg/san_jose_housing/pull/6 for an example config with hundreds of lines of features from a single source table.)

**Comment by thcrock** [comment]
Yeah, this makes sense.

One reason I've been cautious about splitting out the config file is coordinating between different config files: now the experiment config is dependent on this other config, so the hash of the experiment config is far less powerful than it was in figuring out what went on. We can work around this somehow.

Is it also worth using a more compact representation within the YAML here? I see you're using the multi-line array syntax, which for some of these lists may be whitespace overkill.  I don't know if you would prefer this, or if making those changes would actually cut down on the size enough to make these readable.

It's actually possible to handle this outside of triage. Nothing in triage takes a YAML; it takes a dict of a certain structure. The caller can construct this dict however it pleases; a JSON file, or crawling a directory to merge multiple smaller files into one particularly bloated section of the dict. There's discussion about implementing YAML imports like this using PyYAML here: http://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another I'm not specifically recommending any solution in here, but I think this is the layer where it makes a lot of sense to implement config splitting, at least for now.

**Comment by ecsalomon** [comment]
Ok, all of that makes a lot of sense. I agree that perhaps constructing the
dict in the script that calls triage seems to make the most sense and could
work on implementing it in SJ to see how we like it.

**Comment by thcrock** [comment]
On the triage level, we can aid this by exposing a utility that combines a directory structure into a config dict.  The directory structure used can be one that we think represents a good separation of config components.
