### ISSUE TITLE
Dirty Duck Tutorial: dirty-duckling.yaml not found

### ISSUE THREAD

**Issue by rthawkins** [dssg/triage#735]
dirty-duckling.yaml is in the repo and I can view in file explorer, but it doesn't seem that it copied into the container. When running `triage experiment experiments/dirty-duckling.yaml --validate-only`, it returns the following message: "[Errno 2] No such file or directory: 'experiments/dirty-duckling.yaml'" 

OS: Windows 10 Home x64

**Comment by nanounanue** [comment]
Did you run that from `bastion`?

**Comment by nanounanue** [comment]
Closed as not reproducible
