### ISSUE TITLE
Errors using DB config file with CLI

### ISSUE THREAD

**Issue by shaycrk** [dssg/triage#737]
When specifying a config file for accessing the database (either the default or using the parameter), an error is encountered when loading the file using the triage CLI. On quick inspection of cli.py, it looks like:
```
dbfile = open(self.DATABASE_FILE_DEFAULT)
```
should be:
```
dbfile = self.DATABASE_FILE_DEFAULT
```

and:
```
with dbfile:
    dbconfig = yaml.load(dbfile)
```

should be:
```
with open(dbfile, 'r') as dbf:
    dbconfig = yaml.load(dbf)
```

Will try to fix this and test when I have a little time, unless someone else gets to it first.

**Comment by jesteria** [comment]
What's the error/traceback?

In my understanding, the reason for the existing form is that it leaves to `argparse` the responsibility of ensuring that whatever is specified by the `--dbfile` argument is a readable file – and, it opens it.

For that reason, this should be sufficient:

    with dbfile:
        …

(Of course, it is possible that for some reason it is insufficient. But I'm not confident that the changes outlined above will fix things.)

HTH

**Comment by nanounanue** [comment]
Not reproducible. Tested in the new version without problems (with both `DATABASE_FILE_DEFAULT` and `DATABASE_URL`)
