### ISSUE TITLE
Possible redundant database wrapper function

### ISSUE THREAD

**Issue by adunmore** [dssg/triage#751]
From the documentation, create_engine in [general triage utils](https://github.com/dssg/triage/blob/master/src/triage/util/db.py), which wraps a sqlalchemy database engine, seems to be the default database engine source in triage. However, I also found create_pgconn in [postmodeling utils](https://github.com/dssg/triage/blob/master/src/triage/component/postmodeling/contrast/utils/aux_funcs.py). This function returns a psycopg2 engine object.

Is it intentional to have both functions? Or can one be deprecated?

**Comment by nanounanue** [comment]
Just ignore everything in the postmodeling codebase . After we fix **the** bug I will go and try to clean postmodeling
