### ISSUE TITLE
Issues with Multiprocessing:Abnormal termination

### ISSUE THREAD

**Issue by hemanklamba** [dssg/triage#752]
While running MultiCoreExperiment, the following issue was encountered while trying to generate predictions. The model was generated and a corresponding entry was created in model_metadata.models but no predictions for the same model was generated. There could be other errors as well due to multiprocessing, but this was the one that I was encountered.

`INFO:root:Replace flag set; generating new predictions and evaluations formatrix e75531dc8f63533890425ccd8b9b8613-<class 'triage.component.catwalk.storag
e.TestMatrixType'>, and model 110
INFO:root:Checking for model_hash eac457e4b388d01e7bac22bd8a3736c0 in store
INFO:root:Returning model eac457e4b388d01e7bac22bd8a3736c0 from cache
INFO:root:Loaded model 110
ERROR:root:Child failure
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.6.9/lib/python3.6/site-packages/triage/experiments/multicore.py", line 139, in parallelize
    result = next(iterator)
  File "/home/ubuntu/.pyenv/versions/3.6.9/lib/python3.6/site-packages/pebble/pool/base_pool.py", line 211, in next
    raise result
  File "/home/ubuntu/.pyenv/versions/3.6.9/lib/python3.6/site-packages/pebble/pool/base_pool.py", line 234, in chunk_result
    return future.result()
  File "/home/ubuntu/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/ubuntu/.pyenv/versions/3.6.9/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
pebble.common.ProcessExpired: Abnormal termination
INFO:root:Generated predictions for model 110, matrix e75531dc8f63533890425ccd8b9b8613
`

This error was generated while running on m5.12xlarge.

**Comment by thcrock** [comment]
I'm not sure, but 'Abnormal termination' may be an indicator it got killed by the OS (for memory or some other reason)? The system logs may give a clue.

**Comment by nanounanue** [comment]
Agree with @thcrock ... 
It is very similar to the one that @alenastern was facing

**Comment by hemanklamba** [comment]
Yes, I think it is related to memory issues.
Running triage while on a higher memory instance - worked somewhat for me. 
Not sure if I can consistently say that this is true.

**Comment by shaycrk** [comment]
Sounds like an issue with hardward, so will close this, but let's add an issue for better documentation around potential problems/FAQ.
