### ISSUE TITLE
Broken link to temporal validation deep dive in docs

### ISSUE THREAD

**Issue by adunmore** [dssg/triage#773]
The Triage [temporal validation doc](https://dssg.github.io/triage/experiments/temporal-validation/) has a broken link to "Dirty-Duck Temporal Cross-validation". Does anyone know which page in the Dirty Duck docs this might have referenced? It's not clear from the current URL.

**Comment by nanounanue** [comment]
Not really, `dirtyduck` has a `timechop` section but not a _temporal cross validation_ one

**Comment by abell5** [comment]
Just wanted to flag that I was looking for the "Dirty-Duck Temporal Cross-validation" link to pass onto a colleague and ran into this issue. I'll echo @adunmore in asking if anyone knows where it was supposed to point? Thanks!

**Comment by shaycrk** [comment]
Just pushed updated docs, including a fix for this broken link
