### ISSUE TITLE
Add a new parameter to Timechop related to when the data will be available

### ISSUE THREAD

**Issue by nanounanue** [dssg/triage#782]
In some organizations the data is recorded _after_ it really happens, e.g. An event happened on January 1st, but its recording will happen 10 days later.

This affects how the model is trained and used: That data is not available on time

**Comment by ecsalomon** [comment]
That should be handled by the `knowledge_date` in collate, right? If you receive data on the 10th of every month, your knowledge date should be the next 10th

**Comment by nanounanue** [comment]
You're right. I had this discussion with Rayid and Kit and they agree with you :)

Thanks !

**Comment by thcrock** [comment]
What I always wondered is whether or not there was any reason to also use the true date of the event in any modeling. I get the vague sense that this gets taken into account in cohort and label design but I'm wondering if Triage power users have a systematic way of deciding how lag between event dates and knowledge dates get handled in experiment design.

**Comment by ecsalomon** [comment]
This definitely comes into play for things like `time-between-event` features, where we usually want to use event dates (but are typically pre-calculating these features currently). But my first thought is that for cohorts at least, we want to use knowledge dates (to best reflect what would be known at scoring time). For labels, I haven't thought too deeply about it, but I know it was important in the police projects where, e.g., a much later review could change a label.
