### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by thcrock** [dssg/triage#864]

**Comment by nanounanue** [comment]
Are we dropping previous versions of python? Or just adding a new version to it?

**Comment by thcrock** [comment]
numpy is kind of forcing us to drop 3.6 if we want to support 3.9. If we don't upgrade numpy, Triage won't run on 3.9. If we do upgrade numpy, Triage won't run on 3.6.

**Comment by shaycrk** [comment]
Closed via #865
